version: '3.8'

services:
  scheduler:
    build: .
    command: ./scheduler
    environment:
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/jobs?sslmode=disable
    depends_on:
      - redis
      - postgres
    ports:
      - "8080:8080"
      - "9091:9090"

  worker:
    build: .
    command: ./worker
    environment:
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/jobs?sslmode=disable
    depends_on:
      - redis
      - postgres
    deploy:
      replicas: 3

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jobs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  redis_data:
  postgres_data:
  grafana_data: 