global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'scheduler'
    static_configs:
      - targets: ['scheduler:9090']

  - job_name: 'worker'
    static_configs:
      - targets: ['worker:9090']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 