apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          limits:
            cpu: {{ .Values.scheduler.resources.limits.cpu }}
            memory: {{ .Values.scheduler.resources.limits.memory }}
          requests:
            cpu: {{ .Values.scheduler.resources.requests.cpu }}
            memory: {{ .Values.scheduler.resources.requests.memory }} 