apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scheduler-ingress
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scheduler-service
            port:
              number: {{ .Values.service.port }} 